name: Build and Release APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Gradle 9.5
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.5.0'

      - name: Decode stable release keystore
        shell: bash
        run: echo 'MIIK3AIBAzCCCoYGCSqGSIb3DQEHAaCCCncEggpzMIIKbzCCBbYGCSqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFNWPqgTpJ81oy5kmXY3n3DxGIF/QAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQVLqlC2VqOTJNWOsop8vrrgSCBNB7zQmEdzF2EUYuWX3Eph0LGakaya7oILFFvnR2ksUlaoXf9ofnkqsUr4Ak9hl4cjmk1WfTXe4C7cUTTPJbYilpFvk2V4iu1qemCdERrDy4khTJsGWYzwVr7AfeKOw/2htqi+3xEr1bNs71wDzyQdqvlmjsY7B9UoLDbcg/UI1vNPNMwKvjOXIlU+N76bvVQrxRSWQIHIjNJdWEFrD5qxwSgMZf4tp8t2oOGlmpE0uLvViwK0F/PMVOBz33wSLNWxItsKW65sr0LPz8OumacS2wSs8o1YJmm/Is/cXVguG8lkrgkGzUNV/4YWJOwSbPj80h+7lvrWLH796HGIdHf2HNRewzATLHp0skasPf/PWFX55SqpZdtqC7bSRULMXrD80vWr63Ur/u8NsH5NFRp8s/gMVPyu/VbcQ3oNp7z06ZM+WKLA8wnsWyux1S5jZ6KMwOgBC0Gf3hS/iOOU0/bCSdKXMvs+ruNu1f+miDZPMdzHVVMgxO6z9TE6oMRfLrrea/qMKc3CCqMBntUzAFEs5hYyUSKylVeHL3Q9vcnT70iyb9vRYMMIEa+yqxL/HtFoeGp21FYTgEdulEdDKYl5mtY0H9RuYEg0dlG1QXOM9kUw2OYBe5e2p9T9bGOo3RPnnPG5Dq9NGxuffjhKZHdbCr3XB7+3uhPqvzf137dkUkm1EKNjElgl1raVUCNHckdL+ZAcxReSq2SWggxpNuHwXbcF+PSz8tmiPGugd7s0X0D2rVmPnlwot8ertooxEV/65b5dxTvaLTbWer9O6gJQXE7q1RRFsly4hvlxuPT8GjfSU4vIlj/Bvkm5KjZOX4EgSB24nRTLyFOou9nDPaN9eQFVLCQ4MQimFcoC4EwwJIn0uelplSQXt2ehX1fDFHDkVHs3VitakYGuRiNbbwQSSMqmoVnjlmRMMbCW7PVCdJTqHsFZCZxQGpjfNokcHNySVt8nJRFQhps2/otzilFWweXu8U5vsWnlPHpslDiReBmqyqripld41Iln+OF3G7dEMoXXIyjxoXwl51sjlvFpupuOJ/nKCsEcLXGgciR1H/mXfMRIM0xKkUneV+L97fyj5qc2ZUpvu0KGSEa88wojELB1WIcsNR+K5wkDgZ54LiQohutl01S/j78c/ae4l7ZSCGjxSIQf4F2LbIKlSqA8rxzMsadfiWm9BgASryK4fjBC4ahN4tG5YiJJ3X2HBY+aDCq5cWfdi6zSXSS1OenmjLXinfJAE6QEHkqAuv60HcvnX3zVEgXPfu5D3ITfOP9gTvf1yxDjva3kGc9YYmrPUxCCTXNWHWIJGo1ZwLvCkujdmkclqaZylovMHJ+gO1vxeOxOKLodmm9TMcQJaJLlFHo9JjRt4pGw2X5Vv/ylTmc1PtSZu/Nj3/8/m1x1bZ9f2JfB?',' > /dev/null
        "